flowchart RL
    subgraph HexModule
        OutboundPortC
        OutboundPortD
    end
    subgraph OutboundAdapter
        DbRepository -. impl .-> OutboundPortC
        MessagePublisher -. impl .-> OutboundPortD
    end
